var humanmalefirst = {"Adler"", ""Admon", "Adolph", "Ahren", "Aiden", "Aimery", "Alain", "Alard", "Alaric", "Aldous", "Alek", "Alwyn", "Ambert", "Anlow", "Arando", "Benn", "Bram", "Bedrich", "Bertram", "Benvolio", "Bennett", "Brandis", "Cale", "Conrad", "Dalkon", "Daylen", "Dedric", "Del", "Derek", "Dexter", "Dian", "Dirke", "Dodd", "Donn", "Drew", "Dungarth", "Dyrk", "Eandro", "Erik", "Falken", "Feck", "Fenton", "Gallus", "Garvin", "Gregg", "Griswold", "Gryphero", "Hagar", "Hamlin", "Helmut", "Hew", "Jeras", "Jonn", "Kris", "Krynt", "Lavant", "Leyten", "Madian", "Malfier", "Marc", "Markus", "Meklan", "Mikal", "Milos", "Namen", "Navaren", "Nerle", "Nilus", "Ningyan", "Norris", "Pieter", "Quentin", "Quinn", "Raeburn", "Raynard", "Regdar", "Ritter", "Rudolph", "Samm", "Semil", "Sevenson", "Steveren", "Talfen", "Tamond", "Taran", "Tavon", "Tegan", "Thom", "Vanan", "Vincent", "Wendell", "Wil", "Wolfram"};
var humanfemalefirst = {"Ana", "Azura", "Axelle", "Brey", "Brynna", "Carlen", "Cassi", "Clotilda", "Druella", "Eloise", "Eliska", "Eliza", "Enye", "Giselle", "Gwenn", "Hallan", "Jenn", "Kasaki", "Kat", "Kiera", "Lida", "Lorelei", "Luusi", "Megan", "Mika", "Millicent", "Mirabel", "Miri", "Natalie", "Nicola", "Nydia", "Pharana", "Remora", "Rolanda", "Rosalyn", "Rudelle", "Sachil", "Saidi", "Stasi", "Shawna", "Tanika", "Tura", "Tylsa", "Vencia", "Veronica", "Wilhelmina", "Xandrilla", "Zanne"};
var humanlast = {"Arkalis", "Armanci", "Baldric", "Ballard", "Bilger", "Blackstrand", "Brightwater", "Carnavon", "Caskajaro", "Coldshore", "Coyle", "Cresthill", "Cuttlescar", "Daargen", "Dalicarlia", "Danamark", "Donoghan", "Drumwind", "Dunhall", "Ereghast", "Falck", "Fallenbridge", "Faringray", "Fletcher", "Fryft", "Goldrudder", "Grantham", "Graylock", "Gullscream", "Hardy", "Hartman", "Hayward", "Hindergrass", "Iscalon", "Kreel", "Kroft", "Lamoth", "Leerstrom", "Lynchfield", "Moonridge", "Netheridge", "Oakenheart", "Pyncion", "Ratley", "Redraven", "Revenmar", "Roxley", "Rowland", "Sell", "Seratolva", "Shanks", "Shattermast", "Shaulfer", "Silvergraft", "Stavenger", "Stormchapel", "Strong", "Swiller", "Talandro ", "Targana", "Towerfall", "Umbermoor", "Van Devries", "Van Gandt", "Van Hyden", "Varcona", "Varzand", "Voortham", "Vrye", "Webb", "Welfer", "Wilxes", "Wintermere", "Wygarthe", "Zatchet", "Zethergyll"};
var dragmalefirst = {"Andujar", "Arjhan", "Armagan", "Armek", "Arzan", "Axaran", "Balasar", "Belaxarim", "Bharash", "Brevarr", "Djemidor", "Donaar", "Draxan", "Fayal", "Ghesh", "Grax", "Heskan", "Iojad", "Inzul", "Khiraj", "Kreytzen", "Kriv", "Lejek", "Malakith", "Mar", "Medrash", "Nadarr", "Nazir", "Nedam", "Nevek", "Patrin", "Ravaran", "Razaan", "Rhogar", "Sarax", "Sarram", "Savaxis", "Shamash", "Shedinn", "Siangar", "Sirizan", "Sunan", "Szuran", "Tajan", "Tamajon", "Tenahn", "Torinn", "Toxal", "Tzegyr", "Vantajar", "Vharkus", "Xafiq", "Zarkhil", "Zakhijin"};
var dragfemalefirst = {"Akra", "Artana", "Biri", "Daar", "Harann", "Kalas", "Kava", "Khagra", "Korinn", "Leytra", "Mishann", "Myrka", "Nala", "Naya", "Osayah", "Perra", "Raiann", "Sarcha", "Shirren", "Sirivistra", "Sora", "Sufana", "Surina", "Tamara", "Thava", "Vrumadi", "Zovra"};
var dwarfmalefirst = {"Agaro", "Arnan", "Auxlan", "Avamir", "Baelnar", "Balfam", "Bariken", "Borkûl", "Darkûl", "Dolmen", "Dyrnar", "Erag", "Ezegan", "Ferrek", "Garmûl", "Glint", "Ghorvas", "Grimmalk", "Haeltar", "Halagmar", "Halzar", "Hlant", "Korlag", "Krag", "Krim", "Kurman", "Lurtrum", "Malagar", "Mardam", "Maulnar", "Melgar", "Morak", "Orobok", "Rogath", "Roken", "Rozag", "Sabakzar", "Sharak", "Smethykk", "Swargar", "Thorbalt", "Thorin", "Tredigar", "Vabûl", "Vistrum", "Wolvar"};
var dwarffemalefirst = {"Beyla", "Fenryl", "Grenenzel", "Krystolari", "Lokara", "Lurka", "Marnia", "Praxana", "Rokel", "Roksana", "Thurlfara", "Vauldra", "Veklani", "Vronwe", "Zebel"};
var dwarflastnames = {"Ambershard", "Barrelhelm", "Copperhearth", "Deepmiddens", "Drakantal", "Evermead", "Garkalan", "Grimtor", "Hackshield", "Irongull", "Markolak", "Ramcrown", "Rockharvest", "Silvertarn", "Skandalor", "Zarkanan"};





 $("#generate").on("click", function () {
        $("#namePlace").empty()
        birthday = $("#birthday").val()
        first = new Date(birthday.getFullYear(), 0, 1)
        theday = Math.round(((birthday - first) / 1000 / 60 / 60 / 24) + .5, 0)